---
- src: cmprescott.chrome
- src: dev-sec.os-hardening
- src: geerlingguy.ansible
- src: geerlingguy.awx
- src: geerlingguy.docker
- src: geerlingguy.git
- src: geerlingguy.nodejs
- src: geerlingguy.pip
- src: geerlingguy.security
