---
- hosts: localhost
  roles:
    - { role: update, become: yes }
    - { role: dev-sec.os-hardening, become: yes }
    - { role: geerlingguy.security, become: yes }
    - { role: git, become: yes }
